pipeline {
    agent none
    stages {
        stage("Build") {
            agent {
                dockerContainer {
                    image "pack:latest"
                }
            }
            stages {
                stage("Build A") {
                    steps {
                        sh "pack --version"
                    }
                }
            }
        }
    }
}