pipeline {
    agent {
        label "docker-agent"
    }
    stages {
        stage("test") {
            steps {
                script {
                    sh '''
                        pwd
                    '''
                    sh '''
                        ls -al
                    '''
                    sh '''
                        docker run \
                            --rm \
                            --cap-add=CAP_FOWNER \
                            --tmpfs /tmp:rw \
                            --volume ./java/maven/:/workspace:rw \
                            --workdir /workspace \
                            --env HOME="/workspace" \
                            docker.io/buildpacksio/pack:latest build \
                                --trust-builder \
                                paketo-demo-app \
                                --path . \
                                --builder docker.io/paketobuildpacks/builder:base \
                                --buildpack docker.io/paketobuildpacks/java-azure:10

                    '''
                }
            }
        }
    }
}