pipeline {
    agent {
        label "docker-agent"
    }
    stages {
        stage("test") {
            steps {
                script {
                    sh '''
                        docker run \
                            --cap-add=CAP_FOWNER \
                            --tmpfs /tmp:rw \
                            --workdir /workspace \
                            --env HOME="/workspace" \
                            docker.io/buildpacksio/pack:latest --version
                    '''
                }
            }
        }
    }
}